# Generated by Django 5.1.1 on 2024-11-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0001_initial'),
        ('llm', '0002_loggingentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField(verbose_name='User Question')),
                ('response_to_question', models.TextField(verbose_name='Response to Question')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='course_maker.courses')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
