# Generated by Django 5.1.1 on 2024-11-04 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_item', models.TextField(verbose_name='Content Item')),
                ('serial_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_description', models.TextField(verbose_name='Description of course')),
                ('participants_info', models.TextField(verbose_name='Participants and their goals')),
                ('prerequisite_knowledge', models.TextField(verbose_name='Pre-requisite Knowledge')),
                ('content_lang', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish'), ('DE', 'German'), ('UR', 'Urdu')], default='EN', max_length=2, verbose_name='Content Language')),
                ('course_type', models.CharField(choices=[('Pre-Recorded', 'Pre-Recorded'), ('Live Webinar', 'Live Webinar'), ('Hybrid', 'Hybrid')], max_length=15, verbose_name='Course Type')),
                ('knowledge_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=8, verbose_name='Knowledge Level')),
                ('duration', models.CharField(choices=[('1', '1 week'), ('2', '2 weeks'), ('3', '3 weeks'), ('4', '4 weeks')], max_length=1, verbose_name='Duration (in weeks)')),
                ('practice', models.CharField(choices=[('Light', 'Light'), ('Moderate', 'Moderate'), ('Intensive', 'Intensive')], max_length=9, verbose_name='Practice Intensity')),
                ('optimized_for_mooc', models.BooleanField(default=False, verbose_name='MOOC Optimized')),
                ('project_based', models.BooleanField(default=False, verbose_name='Project Based')),
                ('assignment', models.BooleanField(default=False, verbose_name='Assignment Prototypes')),
                ('long_course_support', models.BooleanField(default=False, verbose_name='Long Course Support')),
                ('course_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 - Basic implementation'), (2, 'Level 2 - Rudimentary implementation'), (3, 'Level 3 - Crucial implementation'), (4, 'Level 4 - Key implementation'), (5, 'Level 5 - Substantial implementation'), (6, 'Level 6 - Critical implementation'), (7, 'Level 7 - Leading implementation'), (8, 'Level 8 - Specialist implementation'), (9, 'Level 9 - Innovative implementation')], default=1, null=True, verbose_name='Course Level')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Video', 'Video'), ('Reading', 'Reading')], max_length=7)),
                ('material', models.FileField(blank=True, null=True, upload_to='content_materials/')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration (in minutes)')),
                ('key_points', models.TextField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True, verbose_name='Script')),
                ('content_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course_maker.contentlisting')),
            ],
        ),
        migrations.AddField(
            model_name='contentlisting',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_listings', to='course_maker.courses'),
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField(verbose_name='Learning Outcome')),
                ('tag', models.CharField(max_length=3, verbose_name='Tag')),
                ('number', models.IntegerField()),
                ('sub_items', models.JSONField(default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='course_maker.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('type', models.CharField(choices=[('Single Choice', 'Single Choice'), ('Multiple Choice', 'Multiple Choice')], max_length=15)),
                ('correct_option', models.IntegerField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='course_maker.content')),
            ],
        ),
    ]
