# Generated by Django 5.1.1 on 2024-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='generated_course_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
