# Generated by Django 5.1.1 on 2024-09-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0002_courses_course_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='generated_course_description',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.TextField(),
        ),
    ]
