# Generated by Django 5.1.1 on 2024-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0003_remove_courses_generated_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='sub_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
