# Generated by Django 5.1.1 on 2024-10-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0004_learningoutcome_sub_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcome',
            name='sub_items',
        ),
    ]
