# Generated by Django 5.1.1 on 2024-10-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0005_remove_learningoutcome_sub_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='sub_items',
            field=models.JSONField(default=list),
        ),
    ]
