# Generated by Django 5.1.1 on 2024-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0007_alter_content_key_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='script',
            field=models.TextField(blank=True, null=True, verbose_name='Script'),
        ),
    ]
