# Generated by Django 5.1.1 on 2024-10-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0008_alter_content_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='available_material',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Available baseline material'),
        ),
    ]
