# Generated by Django 5.1.1 on 2024-10-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0009_alter_courses_available_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='available_material_content',
            field=models.TextField(blank=True, null=True, verbose_name='Available Material Content'),
        ),
    ]
