# Generated by Django 5.1.1 on 2024-10-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0011_courses_course_level_alter_courses_content_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 - Basic implementation'), (2, 'Level 2 - Rudimentary implementation'), (3, 'Level 3 - Crucial implementation'), (4, 'Level 4 - Key implementation'), (5, 'Level 5 - Substantial implementation'), (6, 'Level 6 - Critical implementation'), (7, 'Level 7 - Leading implementation'), (8, 'Level 8 - Specialist implementation'), (9, 'Level 9 - Innovative implementation')], default=1, null=True, verbose_name='Course Level'),
        ),
    ]
