# Generated by Django 5.1.1 on 2024-10-30 14:22

import course_maker.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_maker', '0012_alter_courses_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='available_material',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='available_material_content',
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=course_maker.models.upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('file_content', models.TextField(blank=True, null=True, verbose_name='Extracted Content')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material_type', models.CharField(choices=[('textbook', 'Textbook'), ('helping', 'Helping Material')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course_maker.courses')),
            ],
        ),
    ]
