# Generated by Django 5.1.1 on 2024-11-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='audio_book',
            field=models.URLField(blank=True, null=True, verbose_name='Audio Book URL'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_content',
            field=models.TextField(blank=True, null=True, verbose_name='File Content'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('doc', 'Word'), ('audiobook', 'AudioBook')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
