# Generated by Django 5.1.1 on 2024-11-04 11:34

import course_material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0002_coursematerial_audio_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=course_material.models.upload_to),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
