# Generated by Django 5.1.1 on 2024-11-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0003_alter_coursematerial_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('textbook', 'Textbook'), ('helpingbook', 'Helping Book')], max_length=20),
        ),
    ]
